# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
target 'JiuJitsuPlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# firebase
pod 'FirebaseAnalytics' # Google Analytics

# For Analytics without IDFA collection capability, use this pod instead
# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'Firebase/Storage'
pod 'Firebase/Database'

  # Pods for JiuJitsuPlanner
  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        end
      end
    end
  
end
